# Site settings
title: 敏捷博客
email: admin@jsstack.com
description: > # this means to ignore newlines until "baseurl:"
  像对待项目一样的对待每一篇博文。持续迭代的去完善每一个主题。
baseurl: "/agileblog" # the subpath of your site, e.g. /blog/
url: "http://stonesun.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  stonesun

# Build settings
markdown: kramdown
